/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
  docs: [
    'team',
    {
      type: 'category',
      label: '团队文档',
      collapsed: false,
      items: [
        'team/new',
      ]
    }
  ],
  component: [
    {
      type: 'category',
      label: '基础组件',
      collapsed: false,
      items: [
        'component/base/async-button',
      ]
    },
    {
      type: 'category',
      label: '业务组件',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Cetus-Upload',
          items: [
            'component/cetus-upload/demo'
          ]
        },
        
      ]
    }
  ]
};
